### ISSUE TITLE
Basic Dashboard Output

### ISSUE THREAD

**Issue by NathanGrenier** [sonic-howl/frc2024#13]
### 🚀 Summary:

Add some simple wrappers for output to drive station basic dashboard tab (SmartDashboard). This is mostly an introductory exercise for using the robot states and python but will be useful during code development and testing.

### 📋 Tasks:

- [ ] Create wrapper functions to provide outputs to SmartDashboard
- [ ] Create wrapper functions to provide outputs to ShuffleBoard (optional)

**Comment by Portnord** [comment]
Will not proceed further, this was most useful as a training exercise and time will be better spent on at this point in development on providing network tables and boards specific to the other features.
